server:
  servlet:
    context-path: /aureole/secure/api/v1
  port: 8085

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cartv1
    username: cartv1dbadmin
    password: cartv1dbadminpwd

  graphql:
    graphiql:
      enabled: true

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect
    generate-ddl: true
    show-sql: true



